"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import cloudinary
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-nyj^=#gg%luey36f1xtrr-!hpj!z!$)=08u==nmu1y4j1p0va)",
)

# SECURITY WARNING: don't run with debug turned on in production!
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "")
RUNNING_ON_RENDER = bool(RENDER_EXTERNAL_HOSTNAME)
DEBUG = os.getenv("DEBUG", "False").lower() in {
    "1", "true", "yes", "on"
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "wrappdelights.com,www.wrappdelights.com,wrappdelights.onrender.com,localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]

if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'delights_backend.core.store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'delights_backend.core.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'delights_backend.core.store.context_processors.contact_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'delights_backend.core.core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "")
DB_SSL_REQUIRE = os.getenv("DB_SSL_REQUIRE", "True" if RUNNING_ON_RENDER else "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=DB_SSL_REQUIRE,
        )
    }
else:
    if RUNNING_ON_RENDER:
        raise RuntimeError(
            "DATABASE_URL is not set on Render. The app must use the PostgreSQL database service."
        )
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = "/media/"
# Maximum upload size (MB) for admin product image uploads. Can be overridden via env `MAX_UPLOAD_MB`.
try:
    MAX_UPLOAD_MB = int(os.getenv("MAX_UPLOAD_MB", "6"))
except (ValueError, TypeError):
    MAX_UPLOAD_MB = 6
MAX_UPLOAD_SIZE = MAX_UPLOAD_MB * 1024 * 1024
_cloudinary_cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME", "").strip()
_cloudinary_api_key = os.getenv("CLOUDINARY_API_KEY", "").strip()
_cloudinary_api_secret = os.getenv("CLOUDINARY_API_SECRET", "").strip()
USE_CLOUDINARY = all([
    _cloudinary_cloud_name,
    _cloudinary_api_key,
    _cloudinary_api_secret,
])

if USE_CLOUDINARY:
    # Let django-cloudinary-storage handle cloudinary.config() via CLOUDINARY_STORAGE dict
    # Do NOT call cloudinary.config() manually here — it causes double-config and credential clobbering
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': _cloudinary_cloud_name,
        'API_KEY': _cloudinary_api_key,
        'API_SECRET': _cloudinary_api_secret,
        'SECURE': True,
        'PREFIX': '',  # ← Empty prefix prevents public ID mangling (e.g., /media/path/file.jpg breaks Cloudinary)
    }

    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
_configured_media_root = Path(
    os.getenv(
        "MEDIA_ROOT",
        "/var/data/media" if RUNNING_ON_RENDER else str(BASE_DIR / "media"),
    )
)

if USE_CLOUDINARY:
    # MEDIA_ROOT is unused for cloud storage, but kept for compatibility paths.
    MEDIA_ROOT = BASE_DIR / "media"
else:
    # On Render, fall back to local media when /var/data is unavailable or not writable.
    if str(_configured_media_root).startswith("/var/data") and not (
        Path("/var/data").exists() and os.access("/var/data", os.W_OK)
    ):
        MEDIA_ROOT = BASE_DIR / "media"
    else:
        MEDIA_ROOT = _configured_media_root

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

ADMIN_PANEL_PATH = os.getenv("ADMIN_PANEL_PATH", "control-room-admin/").strip("/") + "/"

# Contact info for catalog CTA buttons
WHATSAPP_NUMBER = os.getenv("WHATSAPP_NUMBER", "7397827703")
WHATSAPP_MESSAGE = os.getenv("WHATSAPP_MESSAGE", "Hi, I'm interested in a product from Wrapp Delights!")
PHONE_NUMBER = os.getenv("PHONE_NUMBER", "+91 7397 827 703")  # display-friendly format
PHONE_NUMBER_RAW = os.getenv("PHONE_NUMBER_RAW", "+917397827703")  # tel: link format
SITE_BASE_URL = os.getenv(
    "SITE_BASE_URL",
    f"https://{RENDER_EXTERNAL_HOSTNAME}" if RENDER_EXTERNAL_HOSTNAME else "http://127.0.0.1:8000",
)

if not DEBUG and RUNNING_ON_RENDER:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'delights_backend': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}