# Generated by Django 6.0.3 on 2026-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_active',
            field=models.BooleanField(default=False, help_text='Enable to show discount on this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original MRP before discount', max_digits=10, null=True),
        ),
    ]
