# Generated by Django 6.0.3 on 2026-03-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discount_percent_product_offer_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True, default='')),
                ('link', models.TextField(default='/products/', help_text='URL the banner links to')),
                ('button_text', models.TextField(default='Shop Now')),
                ('bg_color', models.TextField(default='#F5A623', help_text='Hex background color')),
                ('text_color', models.TextField(default='#111111', help_text='Hex text color')),
                ('position', models.IntegerField(default=0, help_text='Order — lower shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='corporaterequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='corporaterequest',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='event_tag',
            field=models.TextField(blank=True, default='', help_text='Event label e.g. Diwali Special, Wedding Season, Corporate Week'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show in Best Sellers section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Featured section on homepage'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='customization_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_active',
            field=models.BooleanField(default=False, help_text='Show discount on this product'),
        ),
    ]
