# Generated by Django 6.0.3 on 2026-03-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_session_key_product_is_new_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Display name e.g. Diwali Premium Hamper')),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundles/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Override price. Leave blank to auto-sum from items', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'predefined_bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredefinedBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.predefinedbundle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'predefined_bundle_items',
            },
        ),
    ]
