# Generated by Django 6.0.3 on 2026-03-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_predefinedbundle_predefinedbundleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('quote', 'Request Corporate Quote'), ('bulk', 'Bulk Order Inquiry'), ('customize', 'Customize for My Company')], default='quote', max_length=20)),
                ('company_name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=25)),
                ('message', models.TextField(blank=True, default='')),
                ('customization_details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hamper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_label', models.CharField(blank=True, default='', help_text="Optional display-only text like 'Starts at INR 1499'", max_length=80)),
                ('min_bulk_quantity', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_event_special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hampers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HamperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'hamper_images',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('section_type', models.CharField(choices=[('corporate_welcome', 'Corporate Welcome Kits'), ('event_hampers', 'Event Hampers'), ('festival_hampers', 'Festival Hampers'), ('featured_hampers', 'Featured Hampers'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'homepage_sections',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_must_have_user_or_session',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='CorporateRequest',
        ),
        migrations.RemoveField(
            model_name='customhamper',
            name='base_product',
        ),
        migrations.RemoveField(
            model_name='customhamper',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hamperitem',
            name='hamper',
        ),
        migrations.RemoveField(
            model_name='hamperitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='predefinedbundleitem',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='predefinedbundleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='hamper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hampers', to='store.category'),
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='hamper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='store.hamper'),
        ),
        migrations.AddField(
            model_name='hamperimage',
            name='hamper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.hamper'),
        ),
        migrations.AddField(
            model_name='hamper',
            name='homepage_sections',
            field=models.ManyToManyField(blank=True, related_name='hampers', to='store.homepagesection'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CustomHamper',
        ),
        migrations.DeleteModel(
            name='HamperItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PredefinedBundle',
        ),
        migrations.DeleteModel(
            name='PredefinedBundleItem',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
