# Generated by Django 6.0.3 on 2026-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_corporateinquiry_hamper_hamperimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamper',
            name='included_items',
            field=models.TextField(blank=True, default='', help_text='One item per line for hamper contents list'),
        ),
        migrations.AlterField(
            model_name='corporateinquiry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
