# Generated by Django 6.0.3 on 2026-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_hamper_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamper',
            name='price_label',
            field=models.CharField(blank=True, default='', help_text="Optional display-only text like 'Price on request'", max_length=80),
        ),
    ]
