# Generated by Django 6.0.3 on 2026-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamper',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hamper',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='homepage_sections', to='store.category'),
        ),
    ]
