# Generated by Django 6.0.3 on 2026-05-02 00:00

from django.db import migrations, models


def copy_single_category_to_m2m(apps, schema_editor):
    Hamper = apps.get_model("store", "Hamper")
    for hamper in Hamper.objects.exclude(category__isnull=True).iterator():
        hamper.categories.add(hamper.category)


def noop_reverse(apps, schema_editor):
    # Preserve mapped data if migration is reversed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_hamper_is_bestseller_hamper_is_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hamper",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assign this product to one or more catalog categories.",
                related_name="multi_category_hampers",
                to="store.category",
            ),
        ),
        migrations.RunPython(copy_single_category_to_m2m, noop_reverse),
    ]
